[package]
name = "dafer-utils"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
polars.workspace = true
anyhow.workspace = true
csv.workspace = true
serde.workspace = true
bincode.workspace = true
