[package]
name = "dafer-utils-ui"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
dafer-utils = { path = "../dafer-utils" }

egui = "0.33.3"
eframe = { version = "0.33.3", features = ["wgpu"] }

